# Generated by Django 4.1.7 on 2023-03-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_hr',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('staff', 'Staff'), ('hr', 'HR')], default='customer', max_length=25, null=True),
        ),
    ]
