# Generated by Django 4.1.7 on 2023-03-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('staff', 'Staff'), ('hr', 'HR')], default='staff', max_length=25, null=True),
        ),
    ]
