# Generated by Django 3.2.18 on 2023-04-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20230331_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
