# Generated by Django 3.2.18 on 2023-04-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='staff', max_length=25, null=True),
        ),
    ]
