# Generated by Django 3.2.18 on 2023-03-23 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_leave_policy', models.FileField(blank=True, null=True, upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='PortData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_leave_per_month', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=265, null=True)),
                ('sick_leave_per_month', models.IntegerField(blank=True, null=True)),
                ('casual_leave_per_month', models.IntegerField(blank=True, null=True)),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.portdata')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, max_length=265, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.portdata')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('nib_card', models.FileField(blank=True, null=True, upload_to='files/')),
                ('nib_number', models.CharField(blank=True, max_length=265, null=True)),
                ('nib_issue', models.DateField(blank=True, null=True)),
                ('nib_expiry', models.DateField(blank=True, null=True)),
                ('passport', models.FileField(blank=True, null=True, upload_to='files/')),
                ('passport_number', models.CharField(blank=True, max_length=265, null=True)),
                ('passport_issue', models.DateField(blank=True, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='files/')),
                ('medical_number', models.CharField(blank=True, max_length=265, null=True)),
                ('medical_issue', models.DateField(blank=True, null=True)),
                ('medical_expiry', models.DateField(blank=True, null=True)),
                ('driver_license', models.FileField(blank=True, null=True, upload_to='files/')),
                ('driver_number', models.CharField(blank=True, max_length=265, null=True)),
                ('driver_issue', models.DateField(blank=True, null=True)),
                ('driver_expiry', models.DateField(blank=True, null=True)),
                ('police_character', models.FileField(blank=True, null=True, upload_to='files/')),
                ('police_number', models.CharField(blank=True, max_length=265, null=True)),
                ('police_issue', models.DateField(blank=True, null=True)),
                ('police_expiry', models.DateField(blank=True, null=True)),
                ('vaccination_card', models.FileField(blank=True, null=True, upload_to='files/')),
                ('vaccination_number', models.CharField(blank=True, max_length=265, null=True)),
                ('vaccination_issue', models.DateField(blank=True, null=True)),
                ('vaccination_expiry', models.DateField(blank=True, null=True)),
                ('other', models.FileField(blank=True, null=True, upload_to='files/')),
                ('other_number', models.CharField(blank=True, max_length=265, null=True)),
                ('other_issue', models.DateField(blank=True, null=True)),
                ('other_expiry', models.DateField(blank=True, null=True)),
                ('safety_certificate', models.FileField(blank=True, null=True, upload_to='files/')),
                ('safety_number', models.CharField(blank=True, max_length=265, null=True)),
                ('safety_issue', models.DateField(blank=True, null=True)),
                ('safety_expiry', models.DateField(blank=True, null=True)),
                ('qualification_certificate', models.FileField(blank=True, null=True, upload_to='files/')),
                ('qualfication_number', models.CharField(blank=True, max_length=265, null=True)),
                ('qualfication_issue', models.DateField(blank=True, null=True)),
                ('qualfication_expiry', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('leave_taken', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.portdata')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
