# Generated by Django 4.1.7 on 2023-03-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_portdata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portdata',
            name='image',
        ),
        migrations.AddField(
            model_name='employeedata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
