# Generated by Django 3.2.18 on 2023-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_companyimsform_imsform_departmentalprocedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicy',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
