# Generated by Django 4.1.7 on 2023-03-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_portdata_image_employeedata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portdata',
            name='driver_license',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='portdata',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='portdata',
            name='nib_card',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='portdata',
            name='other',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='portdata',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='portdata',
            name='police_character',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='portdata',
            name='qualification_certificate',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='portdata',
            name='safety_certificate',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='portdata',
            name='vaccination_card',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
