# Generated by Django 4.1.7 on 2023-03-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_portdata_driver_license_portdata_medical_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portdata',
            name='driver_license',
        ),
        migrations.RemoveField(
            model_name='portdata',
            name='medical_certificate',
        ),
        migrations.RemoveField(
            model_name='portdata',
            name='nib_card',
        ),
        migrations.RemoveField(
            model_name='portdata',
            name='other',
        ),
        migrations.RemoveField(
            model_name='portdata',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='portdata',
            name='police_character',
        ),
        migrations.RemoveField(
            model_name='portdata',
            name='qualification_certificate',
        ),
        migrations.RemoveField(
            model_name='portdata',
            name='safety_certificate',
        ),
        migrations.RemoveField(
            model_name='portdata',
            name='vaccination_card',
        ),
        migrations.AddField(
            model_name='employeedata',
            name='driver_license',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='nib_card',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='other',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='police_character',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='qualification_certificate',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='safety_certificate',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='vaccination_card',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
