# Generated by Django 3.2.18 on 2023-04-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_companypolicy_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicy',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
