# Generated by Django 4.1.7 on 2023-03-18 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_portdata_driver_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.portdata'),
        ),
    ]
