# Generated by Django 3.2.18 on 2023-04-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_companypolicy_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentalprocedure',
            name='user',
        ),
        migrations.AddField(
            model_name='departmentalprocedure',
            name='user_access',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
