# Generated by Django 3.2.18 on 2023-04-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230429_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imsform',
            name='user',
        ),
        migrations.AddField(
            model_name='imsform',
            name='user_access',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
