# Generated by Django 4.1.7 on 2023-03-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_delete_employeedata_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='driver_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='driver_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='driver_number',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='medical_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='medical_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='medical_number',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='nib_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='nib_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='nib_number',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='other_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='other_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='other_number',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='passport_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='passport_number',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='police_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='police_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='police_number',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='qualfication_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='qualfication_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='qualfication_number',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='safety_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='safety_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='safety_number',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='vaccination_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='vaccination_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedata',
            name='vaccination_number',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
