# Generated by Django 3.2.18 on 2023-05-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230429_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imsform',
            name='company_ims',
        ),
        migrations.AddField(
            model_name='imsform',
            name='form_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
