# Generated by Django 3.2.18 on 2023-05-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230503_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyimsform',
            options={'ordering': ['position', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='companypolicy',
            options={'ordering': ['position', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='companyprocedure',
            options={'ordering': ['position', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='departmentalprocedure',
            options={'ordering': ['position', '-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='imsform',
            options={'ordering': ['position', '-updated_at']},
        ),
    ]
