# Generated by Django 3.2.18 on 2023-05-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_role'),
        ('api', '0010_auto_20230503_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('form_name', models.CharField(blank=True, max_length=265, null=True)),
                ('form', models.FileField(blank=True, null=True, upload_to='files/')),
                ('active', models.BooleanField(default=False)),
                ('user_access', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.portdata')),
            ],
            options={
                'ordering': ['position', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IMSProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('procedure_name', models.CharField(blank=True, max_length=265, null=True)),
                ('procedure', models.FileField(blank=True, null=True, upload_to='files/')),
                ('user_access', models.CharField(blank=True, max_length=512, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.portdata')),
            ],
            options={
                'ordering': ['position', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='companyimsform',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companymanual',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departmentalprocedure',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departmentalprocedure',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department'),
        ),
        migrations.AddField(
            model_name='imsform',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CompanyProcedure',
        ),
    ]
