# Generated by Django 4.1.7 on 2023-03-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_employeedata_user_alter_leave_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_leave_policy', models.FileField(blank=True, null=True, upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='company_leave_policy',
        ),
    ]
