# Generated by Django 4.1.7 on 2023-03-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_leavepolicy_company_leave_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavepolicy',
            name='company_leave_policy',
        ),
    ]
