# Generated by Django 3.2.18 on 2023-05-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_companymanual_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymanual',
            name='poistion',
            field=models.IntegerField(default=0),
        ),
    ]
