# Generated by Django 4.1.7 on 2023-03-22 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_remove_leavepolicy_company_leave_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialleave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
