# Generated by Django 3.2.18 on 2023-05-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_poistion_companymanual_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymanual',
            options={'ordering': ['position', '-updated_at']},
        ),
    ]
