# Generated by Django 3.2.18 on 2023-06-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_companymanual_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentalform',
            name='form',
        ),
        migrations.RemoveField(
            model_name='imsform',
            name='ims_form',
        ),
        migrations.RemoveField(
            model_name='imsform',
            name='user_access',
        ),
    ]
