# Generated by Django 4.1.7 on 2023-03-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_leavepolicy_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='status',
        ),
        migrations.AddField(
            model_name='leave',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
