# Generated by Django 4.1.7 on 2023-03-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_leave_status_leave_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.portdata'),
        ),
    ]
