# Generated by Django 4.1.7 on 2023-06-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_location_reporttype_submitto_imsformdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentalformdata',
            name='to_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departmentalformdata',
            name='to_ohse_manager',
            field=models.BooleanField(default=False),
        ),
    ]
