# Generated by Django 4.1.7 on 2023-06-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_departmentalformdata_to_hod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentalformdata',
            name='report_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='departmentalformdata',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
