# Generated by Django 4.1.7 on 2023-03-22 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_employeedata_leave_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicy',
            name='port',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.portdata'),
        ),
    ]
