# Generated by Django 4.1.7 on 2023-03-22 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_leavepolicy_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicy',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.portdata'),
        ),
    ]
