# Generated by Django 4.1.7 on 2023-06-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_role'),
        ('api', '0019_departmentalformdata_report_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentalformdata',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department'),
        ),
        migrations.AddField(
            model_name='departmentalformdata',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
