# Generated by Django 4.1.7 on 2023-06-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_departmentalformdata_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentalformdata',
            name='department',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
