# Generated by Django 4.1.7 on 2023-03-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('nationality', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('zip_code', models.CharField(max_length=256)),
                ('marital_status', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('spouse', models.CharField(max_length=256)),
                ('home_contact', models.CharField(max_length=256)),
                ('ncp_contact', models.CharField(max_length=256)),
                ('nib_number', models.CharField(max_length=256)),
                ('date_of_hire', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=256, null=True)),
                ('department', models.CharField(blank=True, max_length=256, null=True)),
                ('nib_card', models.FileField(blank=True, null=True, upload_to='files/')),
                ('passport', models.FileField(blank=True, null=True, upload_to='files/')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='files/')),
                ('driver_license', models.FileField(blank=True, null=True, upload_to='files/')),
                ('police_character', models.FileField(blank=True, null=True, upload_to='files/')),
                ('vaccination_card', models.FileField(blank=True, null=True, upload_to='files/')),
                ('other', models.FileField(blank=True, null=True, upload_to='files/')),
                ('qualification', models.CharField(max_length=256)),
                ('experience', models.CharField(max_length=256)),
                ('safety_certificate', models.FileField(blank=True, null=True, upload_to='files/')),
                ('qualification_certificate', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
    ]
