# Generated by Django 4.1.7 on 2023-03-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='email',
            field=models.CharField(default='asas', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='full_name',
            field=models.CharField(default='ere', max_length=256),
            preserve_default=False,
        ),
    ]
