# Generated by Django 4.1.7 on 2023-03-11 07:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('employee', '0002_personalinformation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.portdata'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
