# Generated by Django 4.1.7 on 2023-03-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="CardFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("text", "Text"),
                            ("file", "File"),
                            ("switch", "Switch"),
                            ("checkbox", "Checkbox"),
                            ("textarea", "TextArea"),
                            ("dropdown", "Dropdown"),
                            ("number", "Number"),
                            ("date", "Date"),
                        ],
                        default="text",
                        max_length=250,
                        null=True,
                    ),
                ),
                ("mandatory", models.BooleanField(default=False)),
                (
                    "placeholder",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("value", models.CharField(blank=True, max_length=250, null=True)),
                ("options", models.JSONField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fields",
                        to="config.card",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("delete", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Tabs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tabs",
                        to="config.form",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ExtraFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("text", "Text"),
                            ("file", "File"),
                            ("switch", "Switch"),
                            ("checkbox", "Checkbox"),
                            ("textarea", "TextArea"),
                            ("dropdown", "Dropdown"),
                            ("number", "Number"),
                            ("date", "Date"),
                        ],
                        default="text",
                        max_length=250,
                        null=True,
                    ),
                ),
                ("mandatory", models.BooleanField(default=False)),
                (
                    "placeholder",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("value", models.CharField(blank=True, max_length=250, null=True)),
                ("options", models.JSONField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                (
                    "fields",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extra_fields",
                        to="config.cardfields",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="card",
            name="tabs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="card",
                to="config.tabs",
            ),
        ),
    ]
